version: 2
updates:
  - package-ecosystem: pip
    directory: /orgrebase
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /oac-spec
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /orgrebase/documentation
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
